version: "3.7"

services: 
  db:
    container_name: metachron-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: metachron_db
      MYSQL_USER: user
      MYSQL_PASSWORD:
    ports:
      - 10000:3306
    volumes:
      - .data:/var/lib/mysql

  phpmyadmin:
    container_name: metachron-pma
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    links:
      - db:db
    environment: 
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD:
    ports: 
      - 11000:80

volumes:
  data: