version: "3.7"

services: 
  db:
    container_name: metachron-database-courseManagement
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: courseManagement
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 15000:3306
    volumes:
      - courseManagement_data:/var/lib/mysql

  phpmyadmin:
    container_name: metachron-phpmyadmin-courseManagement
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    links:
      - db:db
    environment: 
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password
    ports: 
      - 16000:80

volumes:
  courseManagement_data:

# 192.168.0.7:15000